

package com.javiersc.kotlin.compiler.extensions;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.javiersc.kotlin.compiler.extensions.GenerateKotlinCompilerTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("test-data/box")
@TestDataPath("$PROJECT_ROOT")
public class FakeBoxTestGenerated extends AbstractFakeBoxTest {
  private void run(String fileName) {
    runTest("test-data/box/" + fileName);
  }

  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-data/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("simple-1.kt")
  public void testSimple_1() {
    run("simple-1.kt");
  }
}
