name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Build
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: |
            build
            -Proot.project.name=javiersc-kotlin-template
            -Psemver.stage=snapshot
            -Psemver.scope=patch
